apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  # Minikube 속에서는 결국 NodePort 와 동일함
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000  # NodePort : 30000 ~ 32767
