apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: express-app
        image: lovehyun/express-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: express-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 8000
    name: http
