apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:         # PV 자원 중 어느정도의 자원을 사용할 것인지 명시 
    requests:
      storage: 1Gi   # storage 설정이 1GB로 되어있는데 상위 PV에서 5GB가 할당되어 있음으로
                     # pvc 에서는 pv storage 용량 이하로 설정해야함
                     # 만약 더 큰용량을 설정하면 STATUS가 Pending 상태로 남게되고 생성이 안됨.
  storageClassName: my-storage
  selector:          # 예제 설명을 위해 추가. PVC는 PV를 selector 를 통해 Label 로 확인할 수도 있음
    matchLabels:     # selector 를 사용하지 않고 storageClassName도 사용하지 않을 시 PVC에서 설정한 스펙의 PV가 있는지 자동으로 탐지하여 PV와 연결됨
      storage: pv-test  
