apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - name: my-tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        volumeMounts:                # Volume object를 Pod에 적용
        - mountPath: /VolumeTest     # Mount 경로 설정
          name: my-volume            # volume name에 해당하는 volume을 pod 에 적용
      volumes:                       # volume object 를 생성
        - name: my-volume            # volume object 이름을 my-volume으로 설정
          persistentVolumeClaim:     # PVC를 설정
            claimName: pvc-hostpath  # PVC이름이 pvc-hostpath 인 volume object를 생성
