apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role
  namespace: default
rules:
- apiGroups: [""]  # "" = Default (Core API Group)
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-user-readonly-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: readonly-user
  apiGroup: ""  # Core API Group
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
