apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: tomcat
spec:
  containers:
  - name: tomcat1
    image: tomcat
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    tier: tomcat
spec:
  containers:
  - name: tomcat2
    image: tomcat
    ports:
    - containerPort: 8080
