apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat

spec:
  replicas: 3
  selector:
    matchLabels:
      tier: tomcat

  template:
    metadata:
      labels:
        tier: tomcat
    spec:
      containers:
      - name: tomcat8
        image: tomcat
        ports:
        - containerPort: 8080
