apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  backoffLimit: 3  # 실패 시 재시작 횟수 제한
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 5; exit 1"]
      restartPolicy: Never
  completions: 10  # 총 실행 횟수
  parallelism: 2   # 동시 실행 횟수
