apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod1
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: my-secret-opaque
  restartPolicy: Never
