apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod2
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-secret-opaque
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret-opaque
            key: password
  restartPolicy: Never
